package ExampleLanguage.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Client_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Date_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Project_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x76323df9b7464f38L, 0xa295fd089a3e40d4L, 0x67a20439b3b5e448L), MetaIdFactory.conceptId(0x76323df9b7464f38L, 0xa295fd089a3e40d4L, 0x67a20439b3b5ca6aL), MetaIdFactory.conceptId(0x76323df9b7464f38L, 0xa295fd089a3e40d4L, 0x67a20439b3b5dfe0L)).seal();
}
