package ExampleLanguage.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.AbstractIntentionDescriptor;
import jetbrains.mps.openapi.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.openapi.intentions.IntentionExecutable;
import jetbrains.mps.openapi.intentions.Kind;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import java.util.Collections;
import jetbrains.mps.intentions.AbstractIntentionExecutable;
import ExampleLanguage.behavior.Project__BehaviorDescriptor;
import jetbrains.mps.openapi.intentions.IntentionDescriptor;

public final class AssignStandardID_Intention extends AbstractIntentionDescriptor implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;
  public AssignStandardID_Intention() {
    super(Kind.NORMAL, true, new SNodePointer("r:a550b9c4-46d2-451c-905a-713398f611ff(ExampleLanguage.intentions)", "7467535778008485517"));
  }
  @Override
  public String getPresentation() {
    return "AssignStandardID";
  }
  @Override
  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    return true;
  }
  @Override
  public boolean isSurroundWith() {
    return false;
  }
  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new IntentionImplementation());
    }
    return myCachedExecutable;
  }
  /*package*/ final class IntentionImplementation extends AbstractIntentionExecutable {
    public IntentionImplementation() {
    }
    @Override
    public String getDescription(final SNode node, final EditorContext editorContext) {
      return "Assign Standard ID";
    }
    @Override
    public void execute(final SNode node, final EditorContext editorContext) {
      Project__BehaviorDescriptor.assignStandardID_id6uy13ANHEIb.invoke(node);
    }
    @Override
    public IntentionDescriptor getDescriptor() {
      return AssignStandardID_Intention.this;
    }
  }
}
