package ExampleLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Client = 0;
  public static final int Date = 1;
  public static final int ProgressReport = 2;
  public static final int Project = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x76323df9b7464f38L, 0xa295fd089a3e40d4L);
    builder.put(0x67a20439b3b5e448L, Client);
    builder.put(0x67a20439b3b5ca6aL, Date);
    builder.put(0x67a20439b3b5c8a7L, ProgressReport);
    builder.put(0x67a20439b3b5dfe0L, Project);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
